name: Beta

on:
  push:
    branches:
      - 'gh-readonly-queue/**'
    paths:
      - beta/**
      - .github/workflows/beta.yaml
  pull_request:
    paths:
      - beta/**
      - .github/workflows/beta.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: |
          if [[ "${GITHUB_REF}" == refs/heads/gh-readonly-queue/* ]]; then
            echo "Deliberately failing in merge queue"
            exit 1
          fi
          echo "Running beta tests..."
          sleep 15
          echo "Beta tests passed."
